name: catalog_to_xpublish_dev
channels:
  - conda-forge
  - nodefaults

# a minimal environment for Catalog-To-Xpublish
dependencies:
  - python =3.11

  # For data processing
  - xpublish
  - xarray
  - dask

  # For catalog access
  - intake
  - intake-xarray
  - pystac

  # For API access and data formats
  - fsspec
  - s3fs
  - h5netcdf
  - zarr

  # xpublish plugins
  - xpublish-opendap
  - xpublish-edr

  # Dev tools: Language Server Protocol (LSP)
  - python-lsp-server # LSP extension for Python (pylsp), including:
  - pylsp-mypy  # MyPy type checking for Python >=3.7.
  - pydantic

  # Dev tools: For testing and pre-commit hooks
  - pytest
  - pre-commit

  # Package management
  - conda
  - conda-build
  - conda-libmamba-solver
  - pip

